version: "3.8"
services:
    postgres:
        container_name: postgres_gather_api
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 16988:5432
    nestjs:
        build:
            context: .
        container_name: nestjs_gather_api
        restart: unless-stopped
        ports:
            - 8080:3000
        env_file:
            - .env
        depends_on:
            - postgres
    pgadmin:
        container_name: pgadmin_gather_api
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 16544:5050
        depends_on:
            - nestjs
