version: "3.8"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - nestjs
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 16987:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    nestjs:
        build:
            context: .
        container_name: nestjs
        restart: unless-stopped
        ports:
            - 8080:3000
        env_file:
            - .env
        depends_on:
            - postgres
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 16543:5050
        depends_on:
            - nestjs
volumes:
    postgres_data:
